API:
  ENVIRONMENT: DEVELOPMENT
  NAME: AI_RECOMMENDATION_PREDICTION_MICROSERVICE
  IS_DEBUG: False
  PORT: 9101
  SECRET_KEY: s4GGU7jFnKjgu1LsK7fUdxOp1DUSQ-PVgvr28rBNAHM=

DATABASE:
  #POSTGRESQL local environment
  TYPE: POSTGRESQL
  HOST: localhost
  PORT: 5432
  DATABASE: hb
  USERNAME: postgres
  PASSWORD: 123456